package com.cipherdrive.dna.dto.tem;

import com.cipherdrive.dna.entity.TrustEvolution.Regime;
import com.cipherdrive.dna.service.tem.TEMCalculator.TrustAlert;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Trust Alert Response DTO — Security alert notification.
 *
 * Represents an actionable trust alert generated by the TEM engine
 * when trust dynamics indicate potential identity compromise.
 *
 * Alert levels:
 *   NONE:      No alert — stable operation
 *   INFO:      Minor drift detected — informational only
 *   WARNING:   Significant drift — monitor closely
 *   CRITICAL:  Active degradation — intervention recommended
 *   EMERGENCY: Severe degradation — immediate action required
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TrustAlertResponse {

    /** Alert severity level */
    private TrustAlert alertLevel;

    /** User ID that triggered the alert */
    private Long userId;

    /** Current trust score */
    private BigDecimal currentTrust;

    /** Current regime */
    private Regime regime;

    /** Trust velocity at alert time */
    private BigDecimal trustVelocity;

    /** Trust acceleration at alert time */
    private BigDecimal trustAcceleration;

    /** Trust Degradation Index at alert time */
    private BigDecimal tdiComposite;

    /** Human-readable alert description */
    private String message;

    /** Recommended actions for this alert level */
    private String recommendedAction;

    /** Whether the alert requires immediate human intervention */
    private boolean requiresIntervention;

    /** Alert timestamp */
    private LocalDateTime timestamp;

    /**
     * Get recommended action based on alert level.
     */
    public static String getRecommendedAction(TrustAlert alert) {
        return switch (alert) {
            case NONE -> "No action required";
            case INFO -> "Monitor trust trajectory — minor drift detected";
            case WARNING -> "Review recent user activity — significant trust drift observed";
            case CRITICAL -> "Trigger step-up authentication — active trust degradation detected";
            case EMERGENCY -> "Force re-authentication and session review — severe trust degradation";
        };
    }
}
