package com.cipherdrive.dna.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Computed Digital DNA profile snapshots per user per session.
 * Maps to: digital_dna table
 *
 * Generated by the Digital DNA Engine's 7-stage pipeline:
 *   1. Event Ingestion → 2. Dimension Extraction → 3. Normalization
 *   4. AHP Weighting → 5. Entropy Weighting → 6. Composite Fusion
 *   7. Similarity & Drift Computation
 */
@Entity
@Table(name = "digital_dna", indexes = {
        @Index(name = "ix_dna_user_computed", columnList = "user_id, computed_at DESC"),
        @Index(name = "ix_dna_session_id", columnList = "session_id"),
        @Index(name = "ix_dna_drift_regime", columnList = "drift_regime, computed_at DESC"),
        @Index(name = "ix_dna_cosine_sim", columnList = "cosine_similarity"),
        @Index(name = "ix_dna_baseline", columnList = "baseline_dna_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"user", "session", "baselineProfile", "identityConfidenceScores"})
public class DigitalDNA {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(name = "fk_digital_dna_user_id"))
    private User user;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "session_id", nullable = false, foreignKey = @ForeignKey(name = "fk_digital_dna_session_id"))
    private Session session;

    @Column(name = "computation_window_ms", nullable = false)
    @Builder.Default
    private Integer computationWindowMs = 300000; // 5 minutes

    // ── 7 Behavioral Dimension Vectors (JSON) ──

    @Column(name = "keystroke_vector", nullable = false, columnDefinition = "JSON")
    private String keystrokeVector;

    @Column(name = "mouse_vector", nullable = false, columnDefinition = "JSON")
    private String mouseVector;

    @Column(name = "navigation_vector", nullable = false, columnDefinition = "JSON")
    private String navigationVector;

    @Column(name = "file_op_vector", nullable = false, columnDefinition = "JSON")
    private String fileOpVector;

    @Column(name = "temporal_vector", nullable = false, columnDefinition = "JSON")
    private String temporalVector;

    @Column(name = "device_vector", nullable = false, columnDefinition = "JSON")
    private String deviceVector;

    @Column(name = "context_vector", nullable = false, columnDefinition = "JSON")
    private String contextVector;

    // ── Composite Scores ──

    @Column(name = "combined_vector", nullable = false, columnDefinition = "JSON")
    private String combinedVector;

    @Column(name = "cosine_similarity", nullable = false, precision = 10, scale = 8)
    private BigDecimal cosineSimilarity;

    @Column(name = "drift_score", nullable = false, precision = 10, scale = 8)
    private BigDecimal driftScore;

    @Column(name = "drift_regime", nullable = false, length = 16)
    @Enumerated(EnumType.STRING)
    private DriftRegime driftRegime;

    // ── Weight Configuration ──

    @Column(name = "ahp_weights", nullable = false, columnDefinition = "JSON")
    private String ahpWeights;

    @Column(name = "entropy_weights", nullable = false, columnDefinition = "JSON")
    private String entropyWeights;

    @Column(name = "composite_weights", nullable = false, columnDefinition = "JSON")
    private String compositeWeights;

    // ── Baseline Reference (self-referencing) ──

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "baseline_dna_id", foreignKey = @ForeignKey(name = "fk_digital_dna_baseline"))
    private DigitalDNA baselineProfile;

    // ── Metadata ──

    @Column(name = "sample_count", nullable = false)
    private Integer sampleCount;

    @Column(name = "algorithm_version", nullable = false, length = 16)
    @Builder.Default
    private String algorithmVersion = "2.0";

    @CreationTimestamp
    @Column(name = "computed_at", nullable = false, updatable = false)
    private LocalDateTime computedAt;

    // ── Relationships ──

    @OneToMany(mappedBy = "dnaProfile", fetch = FetchType.LAZY)
    @Builder.Default
    private java.util.List<IdentityConfidence> identityConfidenceScores = new java.util.ArrayList<>();

    // ── Enum ──

    public enum DriftRegime {
        /** Current profile closely matches baseline — no action needed */
        NORMAL,
        /** Minor deviation detected — monitor and log */
        LOW_DRIFT,
        /** Significant deviation — flag for ICS recalculation */
        HIGH_DRIFT,
        /** Critical deviation — trigger immediate security challenge */
        ANOMALY
    }
}
